version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo yarn global add greenkeeper-lockfile@1
      - run: yarn install
      - run: greenkeeper-lockfile-update
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run lint
      - run: yarn run build
      - run: greenkeeper-lockfile-upload
